<?php

namespace Database\Seeders;

use App\Models\Portfolio;
use Illuminate\Database\Seeder;

class PortfolioSeeder extends Seeder
{
    public function run(): void
    {
        $portfolios = [
            ['title' => 'E-Commerce Platform', 'slug' => 'ecommerce-platform', 'short_description' => 'A full-featured online shopping platform with inventory management and payment integration.', 'description' => "Built a comprehensive e-commerce platform for a retail company. The platform features product management, shopping cart, payment gateway integration, order tracking, and an admin dashboard.\n\nKey features:\n- Product catalog with categories and filters\n- Shopping cart and checkout\n- PayPal and Stripe integration\n- Admin dashboard with analytics\n- Inventory management system", 'client_name' => 'RetailMax Inc.', 'technologies_used' => '["Laravel","Vue.js","PostgreSQL","Stripe"]', 'completion_date' => '2025-11-15', 'status' => true, 'featured' => true],
            ['title' => 'Hospital Management System', 'slug' => 'hospital-management-system', 'short_description' => 'A comprehensive system for managing patient records, appointments, and hospital operations.', 'description' => "Developed a hospital management system that streamlines patient registration, appointment scheduling, medical records management, and billing.\n\nKey features:\n- Patient registration and management\n- Appointment scheduling\n- Electronic medical records\n- Pharmacy management\n- Billing and insurance processing", 'client_name' => 'City Medical Center', 'technologies_used' => '["Laravel","React","MySQL","Docker"]', 'completion_date' => '2025-08-20', 'status' => true, 'featured' => true],
            ['title' => 'Mobile Banking App', 'slug' => 'mobile-banking-app', 'short_description' => 'A secure mobile banking application with real-time transaction processing.', 'description' => "Created a mobile banking application that allows users to manage their accounts, transfer funds, pay bills, and track expenses securely.\n\nKey features:\n- Account management\n- Fund transfers\n- Bill payments\n- Transaction history\n- Push notifications\n- Biometric authentication", 'client_name' => 'FinSecure Bank', 'technologies_used' => '["React Native","Node.js","PostgreSQL","Redis"]', 'completion_date' => '2025-06-10', 'status' => true, 'featured' => true],
            ['title' => 'Real Estate Portal', 'slug' => 'real-estate-portal', 'short_description' => 'A property listing and management platform with virtual tour capabilities.', 'description' => "Built a real estate portal that connects buyers, sellers, and agents. The platform includes property listings, virtual tours, and communication tools.\n\nKey features:\n- Property listing with images\n- Virtual 360-degree tours\n- Agent profiles and dashboards\n- Advanced search and filters\n- Messaging system", 'client_name' => 'HomeFinders Realty', 'technologies_used' => '["Laravel","Vue.js","PostgreSQL","AWS S3"]', 'completion_date' => '2025-04-05', 'status' => true, 'featured' => true],
            ['title' => 'Learning Management System', 'slug' => 'learning-management-system', 'short_description' => 'An online learning platform with course creation, enrollment, and progress tracking.', 'description' => "Developed an LMS that enables educational institutions to create, manage, and deliver online courses with comprehensive tracking and reporting.\n\nKey features:\n- Course creation and management\n- Student enrollment\n- Video streaming\n- Quiz and assignment system\n- Progress tracking and certificates", 'client_name' => 'EduTech Institute', 'technologies_used' => '["Laravel","React","PostgreSQL","FFmpeg"]', 'completion_date' => '2025-02-18', 'status' => true, 'featured' => false],
            ['title' => 'Fleet Management System', 'slug' => 'fleet-management-system', 'short_description' => 'A real-time fleet tracking and management system with GPS integration.', 'description' => "Created a fleet management system with real-time GPS tracking, route optimization, vehicle maintenance scheduling, and driver management.\n\nKey features:\n- Real-time GPS tracking\n- Route optimization\n- Maintenance scheduling\n- Driver performance analytics\n- Fuel consumption tracking", 'client_name' => 'LogiTrans Logistics', 'technologies_used' => '["Laravel","Vue.js","PostgreSQL","WebSocket"]', 'completion_date' => '2024-12-01', 'status' => true, 'featured' => false],
            ['title' => 'Social Media Analytics Dashboard', 'slug' => 'social-media-analytics', 'short_description' => 'A comprehensive analytics dashboard for tracking social media performance and engagement.', 'description' => "Built a social media analytics platform that aggregates data from multiple platforms and provides actionable insights.\n\nKey features:\n- Multi-platform integration\n- Engagement metrics\n- Content performance analysis\n- Competitor tracking\n- Automated reporting", 'client_name' => 'BrandWatch Agency', 'technologies_used' => '["Laravel","React","PostgreSQL","Chart.js"]', 'completion_date' => '2024-09-15', 'status' => true, 'featured' => false],
            ['title' => 'Inventory Management System', 'slug' => 'inventory-management-system', 'short_description' => 'An automated inventory tracking system with barcode scanning and low-stock alerts.', 'description' => "Developed an inventory management system with barcode scanning, automated stock tracking, and real-time reporting for a manufacturing company.\n\nKey features:\n- Barcode scanning integration\n- Real-time stock tracking\n- Low-stock alerts\n- Purchase order management\n- Reporting and analytics", 'client_name' => 'ManufactPro Ltd.', 'technologies_used' => '["Laravel","Vue.js","PostgreSQL","WebSocket"]', 'completion_date' => '2024-07-20', 'status' => true, 'featured' => false],
        ];

        foreach ($portfolios as $portfolio) {
            Portfolio::create($portfolio);
        }
    }
}
