@extends('layouts.admin') @section('title', 'Edit Team Member') @section('header', 'Edit Team Member')
@section('content')
<div class="bg-white rounded-xl shadow-sm border border-gray-200 p-6 max-w-3xl">
    <form method="POST" action="{{ route('admin.team-members.update', $teamMember) }}" enctype="multipart/form-data" class="space-y-5">@csrf @method('PUT')
        <div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-gray-700 mb-1">Name *</label><input type="text" name="name" value="{{ old('name', $teamMember->name) }}" required class="w-full px-4 py-2.5 border border-gray-300 rounded-lg"></div><div><label class="block text-sm font-medium text-gray-700 mb-1">Position</label><input type="text" name="position" value="{{ old('position', $teamMember->position) }}" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg"></div></div>
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Biography</label><textarea name="biography" rows="5" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg">{{ old('biography', $teamMember->biography) }}</textarea></div>
        <div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-gray-700 mb-1">Email</label><input type="email" name="email" value="{{ old('email', $teamMember->email) }}" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg"></div><div><label class="block text-sm font-medium text-gray-700 mb-1">Image</label>@if($teamMember->image)<div class="mb-2"><img src="{{ asset($teamMember->image) }}" class="h-16 w-16 rounded-full object-cover"></div>@endif<input type="file" name="image" accept="image/*" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg"></div></div>
        <div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-gray-700 mb-1">LinkedIn URL</label><input type="url" name="linkedin_url" value="{{ old('linkedin_url', $teamMember->linkedin_url) }}" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg"></div><div><label class="block text-sm font-medium text-gray-700 mb-1">GitHub URL</label><input type="url" name="github_url" value="{{ old('github_url', $teamMember->github_url) }}" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg"></div></div>
        <div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-gray-700 mb-1">Sort Order</label><input type="number" name="sort_order" value="{{ old('sort_order', $teamMember->sort_order) }}" min="0" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg"></div><div><label class="flex items-center gap-2 mt-6"><input type="checkbox" name="status" value="1" {{ $teamMember->status ? 'checked' : '' }} class="rounded border-gray-300 text-blue-600"><span class="text-sm text-gray-700">Active</span></label></div></div>
        <div class="flex gap-3"><button type="submit" class="px-6 py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm">Update</button><a href="{{ route('admin.team-members.index') }}" class="px-6 py-2.5 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 text-sm">Cancel</a></div>
    </form>
</div>
endsection
