@extends('layouts.admin') @section('title', 'Edit Post') @section('header', 'Edit Post')
@section('content')
<div class="bg-white rounded-xl shadow-sm border border-gray-200 p-6 max-w-3xl">
    <form method="POST" action="{{ route('admin.blog-posts.update', $blogPost) }}" enctype="multipart/form-data" class="space-y-5">@csrf @method('PUT')
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Title *</label><input type="text" name="title" value="{{ old('title', $blogPost->title) }}" required class="w-full px-4 py-2.5 border border-gray-300 rounded-lg">@error('title')<p class="text-red-500 text-xs mt-1">{{ $message }}</p>@enderror</div>
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Slug</label><input type="text" name="slug" value="{{ old('slug', $blogPost->slug) }}" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg"></div>
        <div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-gray-700 mb-1">Category</label><select name="category_id" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg"><option value="">None</option>@foreach($categories as $cat)<option value="{{ $cat->id }}" {{ (old('category_id', $blogPost->category_id) == $cat->id) ? 'selected' : '' }}>{{ $cat->name }}</option>@endforeach</select></div><div><label class="block text-sm font-medium text-gray-700 mb-1">Published At</label><input type="datetime-local" name="published_at" value="{{ old('published_at', $blogPost->published_at?->format('Y-m-d\TH:i')) }}" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg"></div></div>
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Excerpt</label><textarea name="excerpt" rows="3" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg">{{ old('excerpt', $blogPost->excerpt) }}</textarea></div>
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Content</label><textarea name="content" rows="12" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg">{{ old('content', $blogPost->content) }}</textarea></div>
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Featured Image</label>@if($blogPost->featured_image)<div class="mb-2"><img src="{{ asset($blogPost->featured_image) }}" class="h-24 w-auto rounded"></div>@endif<input type="file" name="featured_image" accept="image/*" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg">@error('featured_image')<p class="text-red-500 text-xs mt-1">{{ $message }}</p>@enderror</div>
        <div><label class="flex items-center gap-2"><input type="checkbox" name="status" value="1" {{ $blogPost->status ? 'checked' : '' }} class="rounded border-gray-300 text-blue-600"><span class="text-sm text-gray-700">Published</span></label></div>
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Meta Title</label><input type="text" name="meta_title" value="{{ old('meta_title', $blogPost->meta_title) }}" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg"></div>
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Meta Description</label><textarea name="meta_description" rows="2" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg">{{ old('meta_description', $blogPost->meta_description) }}</textarea></div>
        <div class="flex gap-3"><button type="submit" class="px-6 py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm">Update</button><a href="{{ route('admin.blog-posts.index') }}" class="px-6 py-2.5 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 text-sm">Cancel</a></div>
    </form>
</div>
@endsection
